# Generated by Django 5.2.6 on 2026-06-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trace_It', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('GEOFENCE', 'Geofence Breach'), ('BATTERY', 'Low Battery'), ('TEMPERATURE', 'Temperature Alert'), ('SPEED', 'Speed Alert'), ('STATIONARY', 'Stationary Alert'), ('HEALTH', 'Health Alert'), ('SENSOR', 'Sensor Error')], max_length=20),
        ),
        migrations.CreateModel(
            name='BiometricReading',
            fields=[
                ('reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('spo2_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accel_x', models.IntegerField(blank=True, null=True)),
                ('accel_y', models.IntegerField(blank=True, null=True)),
                ('accel_z', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_status', models.CharField(default='OK', max_length=50)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trace_It.location')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trace_It.trackingtag')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
