# Generated by Django 4.2.30 on 2026-06-16 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trace_It', '0002_alter_alert_alert_type_biometricreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingtag',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
