from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('ranger/login/', views.ranger_login, name='ranger_login'),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('logout/', views.logout_view, name='logout'),
    path('index/', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('animal/<int:animal_id>/', views.animal_detail, name='animal_detail'),
    path('animal/add/', views.add_animal, name='add_animal'),
    path('animal/<int:animal_id>/edit/', views.edit_animal, name='edit_animal'),
    path('animal/<int:animal_id>/delete/', views.delete_animal, name='delete_animal'),
    path('animals/', views.animal_list, name='animal_list'),
    path('animal/<int:animal_id>/history/', views.location_history, name='location_history'),
    path('map/', views.map_view, name='map_view'),
    path('tags/', views.tag_list, name='tag_list'),
    path('tag/add/', views.add_tag, name='add_tag'),
    path('tag/<int:tag_id>/assign/', views.assign_tag, name='assign_tag'),
    path('geofences/', views.geofence_list, name='geofence_list'),
    path('geofence/add/', views.add_geofence, name='add_geofence'),
    path('geofence/<int:geofence_id>/edit/', views.edit_geofence, name='edit_geofence'),
    path('geofence/<int:geofence_id>/delete/', views.delete_geofence, name='delete_geofence'),
    path('alerts/', views.alerts, name='alerts'),
    path('alert/<int:alert_id>/resolve/', views.resolve_alert, name='resolve_alert'),
    path('export/locations/', views.export_locations_csv, name='export_locations_csv'),
    path('export/alerts/', views.export_alerts_csv, name='export_alerts_csv'),
    path('export/alerts/json/', views.export_alerts, name='export_alerts'),
    path('audit-log/', views.audit_log, name='audit_log'),
    path('users/', views.manage_users, name='manage_users'),
    path('users/create-ranger/', views.create_ranger, name='create_ranger'),
    path('users/toggle-role/<int:user_id>/', views.toggle_user_role, name='toggle_user_role'),
    path('users/toggle-status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('geofence/setup-demo/', views.setup_demo_geofences, name='setup_demo_geofences'),
    path('api/iot/ingest/', views.iot_ingest, name='iot_ingest'),
    path('api/iot/register/', views.iot_register, name='iot_register'),
    path('api/iot/status/<str:tag_serial>/', views.iot_status, name='iot_status'),
]